id: a0eb01863bc448aebf99c6c2021f5031
initial_creation_type: ocr
source_metadata:
  volumes:
    b1d5466c6bfe4fa08245ddf9dd6c4c1a:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: དམྱལ་བ་ནས་འདོན་པ།
      total_pages: 1539
      volume_number: 1
