id: D9F933FD5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:09:55+00:00'
last_modified: '2022-05-26T06:08:47.680019+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    2aef:
      image_group_id: I1PD95846
      title: དམྱལ་བ་ནས་འདོན་པ།
      total_pages: 1539
      order: 1
      base_file: 2aef.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
